/* eslint-disable @next/next/no-page-custom-font */
import "styles/globals.css";
import type { AppProps } from "next/app";
import { Header, Auth } from "components";
import { Provider } from "react-redux";
import { useStore } from "../store/store";
import Head from "next/head";
import { saveState } from "../store/localStorage";
import useRedux from "util/useRedux";
import { Provider as NextAuthProvider } from 'next-auth/client';
import { SocketProvider } from "socketProvider";
import io from 'socket.io-client';


const socket = io();
const MyApp = ({ Component, pageProps }: AppProps) => {
  const store = useStore(pageProps.initialReduxState);
  store.subscribe(() => {
    saveState(store.getState());
  });
  return (

      <Provider store={store}>
        <NextAuthProvider session={pageProps.session}>
            <SocketProvider value={socket}>
              <Head>
                <title>Balkan Dating</title>
                <meta name="description" content="Generated by developers from Nis" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com"></link>
                <link
                  href="https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700;900&family=Poppins:wght@300;400;500;600;700&display=swap"
                  rel="stylesheet"
                />
              </Head>
              <Header />
              <Auth />
              <Component {...pageProps} />
          </SocketProvider>
        </NextAuthProvider>
      </Provider>
    
  );
};

export default MyApp;
